# 
# MAKEFILE for 5.8GHz Video Receiver Module 
#
# Commands:
#	make all - Compiles the source and produces a HEX file
#   make program - Programs the hex file into the ATTiny24 using AVRDUDE and USBasp programmer tool
#   make size - Returns the program flash usage. Note, this doesn't give RAM usage.
#   make clean - Cleans all hex and other object output files
# 
# 
# The MIT License (MIT)
#
# Copyright (c) 2014 Simon Chambers
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

all: main

main: fs_skyrf_58g-main.c
	avr-gcc -Wall -g -Os -c -mmcu=attiny24a fs_skyrf_58g-main.c
	avr-gcc -mmcu=attiny24a fs_skyrf_58g-main.o -o fs_skyrf_58g-main.elf
	avr-objcopy -O ihex -R .eeprom fs_skyrf_58g-main.elf fs_skyrf_58g-main.hex

program: all
	avrdude -c usbasp -P usb -p t24 -U flash:w:fs_skyrf_58g-main.hex

program-test: all
	avrdude -n -c usbasp -P usb -p t24 -U flash:w:fs_skyrf_58g-main.hex

read-fuses:
	avrdude -p t24 -c usbtiny -U lfuse:r:-:h -U hfuse:r:-:h -U efuse:r:-:h -U lock:r:-:h
	
size:
	avr-size --format=avr --mcu=attiny24a fs_skyrf_58g-main.elf

clean:
	rm -rf *o fs_skyrf_58g-main
	rm -rf *elf fs_skyrf_58g-main
	rm -rf *hex fs_skyrf_58g-main
